name: Build-Test
run-name: ${{ github.actor }} Building and Testing
on:
  push:
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the Docker image
        run: docker build -t dash .
      - name: Start Docker Compose
        run: |
          docker compose up dash -d
          docker compose ps  # Check the status of the services
      - name: Testing
        run: docker compose exec -it dash pytest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: st125490/ml_logit_3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: st125490/ml_logit_3:v2
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PASSWORD }}
          proxy_passphrase: ${{ secrets.PASSPHRASE }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Running commands on the remote server..."
            docker pull st125490/ml_logit_3:v2 &&
            tag=${{ github.ref_name }} && docker compose -f st125490/docker-compose.yaml down &&
            tag=${{ github.ref_name }} && docker compose -f st125490/docker-compose.yaml up -d
#i am tired       