name: Build-Test
# Name of this run
run-name: ${{ github.actor }} Building and Testing
# When this action will be trigger
# I want to do this when we push new change with tag.
# This tag will be used next when we build and push the image to dockerhub
on:
  push:
    braches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t app .
      - name: Compose up
        run: docker compose up -d
      - name: Testing
        run: docker compose exec -it dash pytest 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_ST125490}}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: st125490/ml_logit_3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile
          push: true
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE}}
        
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PASSWORD }}
          proxy_passphrase: ${{ secrets.PASSPHRASE }}
          proxy_key: ${{secrets.SSH_PRIVATE_KEY}}
          
          script: |
            docker pull st125490/ml_logit_3_:latest
            tag=${{ github.ref_name }} docker compose -f st125490/docker-compose.yaml down
            tag=${{ github.ref_name }} docker compose -f st125490/docker-compose.yaml up -d   
            
                  
